name: Hello world
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: |
        echo "This is no what i meant to be"
        uname -i
        who
        date
