name: Github action demo
on: 
  push:
    # branches:
    #   - main
    #   - develop
    #   - 'release/**'
jobs:
  Actoins_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print index.html
        run: cat index.html
        # run: echo "My name is ${{ vars.MY_NAME }}"
        
  # Test:
  #   runs-on: ubuntu-latest
  #   needs: Build
  #   steps:
  #     - name: Testing
  #       run: echo "Testing thammudu"

  # Deploy:
  #   runs-on: ubuntu-latest
  #   needs: Test
  #   steps:
  #     - name: Step Deploy
  #       run: echo "dhana dhan"
